
version: '3.1'

services:
  
    rabbitmq:
      image: 'rabbitmq:3.6-management-alpine'
      container_name: brutus-user-rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
          
    redis:
      image: 'redis:6.0.5-alpine'
      container_name: brutus-user-redis
      ports:
        - "6379:6379"

