version: '2.0'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  
  adminer:
    image: adminer
    restart: always
    ports:
    - 8081:8080