version: '2.0'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  
  adminer:
    image: adminer
    restart: always
    ports:
    - 8081:8080
      
  rabbitMq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    